version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
